chore: Truing up files with pre-commit hooks
Scanning all files with pre-commit hooks and fixing all found issues.  Mostly spelling or formatting related.

diff --git a/bin/crypt b/bin/crypt
--- a/bin/crypt
+++ b/bin/crypt
@@ -6,7 +6,7 @@ sourced=0
 if [[ -n "${ZSH_VERSION:-}" ]]; then
   [[ ${ZSH_EVAL_CONTEXT:-} =~ :file$ ]] && sourced=1 || sourced=0
 elif [[ -n "${BASH_VERSION:-}" ]]; then
-  (return 0 2> /dev/null) && sourced=1 || sourced=0
+  (return 0 2>/dev/null) && sourced=1 || sourced=0
 else # All other shells: examine $0 for known shell binary filenames.
   # Detects `sh` and `dash`; add additional shell filenames as needed.
   case ${0##*/} in sh | -sh | dash | -dash) sourced=1 ;; *) sourced=0 ;; esac
@@ -48,7 +48,7 @@ checkInternet() {
   } # query github with a get request
 }
 
-## This function determines which http get tool the system has installed and returns an error if there isnt one
+## This function determines which http get tool the system has installed and returns an error if there isn't one
 getConfiguredClient() {
   if command -v curl &>/dev/null; then
     configuredClient="curl"
@@ -59,7 +59,7 @@ getConfiguredClient() {
   elif command -v fetch &>/dev/null; then
     configuredClient="fetch"
   else
-    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
+    echo "Error: This tool requires either curl, wget, httpie or fetch to be installed." >&2
     return 1
   fi
 }
@@ -98,9 +98,9 @@ decrypt() {
 update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
-  # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets"                                                                                                                               #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein"                                                                                                                            #username that hosts the repostiory ex. alexanderepstein
+  # To test the tool enter in the default values that are in the examples for each variable
+  repositoryName="Bash-Snippets"                                                                                                                               #Name of repository to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                            #username that hosts the repository ex. alexanderepstein
   nameOfInstallFile="install.sh"                                                                                                                               # change this if the installer file has a different name be sure to include file extension if there is one
   latestVersion=$(httpGet https://api.github.com/repos/${githubUserName}/${repositoryName}/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
@@ -140,11 +140,11 @@ update() {
           exit 1
         }
         git checkout "v${latestVersion}" 2>/dev/null || git checkout "${latestVersion}" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
-        chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
+        chmod a+x install.sh #this might be necessary in your case but wasn't in mine.
         ./"${nameOfInstallFile}" "update" || exit 1
         cd ..
         rm -r -f "${repositoryName}" || {
-          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/${repositoryName} delete this directory with sudo"
+          echo "Permissions Error: update successful but cannot delete temp files located at ~/${repositoryName} delete this directory with sudo"
           exit 1
         }
       else
@@ -174,13 +174,13 @@ EOF
 
 checkOpenSSL || exit 1
 
-while getopts "huve:d:" opt; do ## alows for using options in bash
+while getopts "huve:d:" opt; do ## allows for using options in bash
   case ${opt} in
   e) ## when trying to encrypt run this
     if [[ ${state} != "decrypt" ]]; then
       state="encrypt"
     else
-      echo "Error: the -d and -e options are mutally exclusive" >&2
+      echo "Error: the -d and -e options are mutually exclusive" >&2
       exit 1
     fi
     if [[ $# -ne 3 ]]; then
@@ -196,7 +196,7 @@ while getopts "huve:d:" opt; do ## alows for using options in bash
     if [[ ${state} != "encrypt" ]]; then
       state="decrypt"
     else
-      echo "Error: the -e and -d options are mutally exclusive" >&2
+      echo "Error: the -e and -d options are mutually exclusive" >&2
       exit 1
     fi
     if [[ $# -ne 3 ]]; then
diff --git a/bin/cryptocurrency b/bin/cryptocurrency
--- a/bin/cryptocurrency
+++ b/bin/cryptocurrency
@@ -7,7 +7,7 @@ sourced=0
 if [[ -n "${ZSH_VERSION:-}" ]]; then
   [[ ${ZSH_EVAL_CONTEXT:-} =~ :file$ ]] && sourced=1 || sourced=0
 elif [[ -n "${BASH_VERSION:-}" ]]; then
-  (return 0 2> /dev/null) && sourced=1 || sourced=0
+  (return 0 2>/dev/null) && sourced=1 || sourced=0
 else # All other shells: examine $0 for known shell binary filenames.
   # Detects `sh` and `dash`; add additional shell filenames as needed.
   case ${0##*/} in sh | -sh | dash | -dash) sourced=1 ;; *) sourced=0 ;; esac
@@ -35,7 +35,7 @@ old="false"
 currentVersion="1.22.0"
 unset configuredClient
 
-## This function determines which http get tool the system has installed and returns an error if there isnt one
+## This function determines which http get tool the system has installed and returns an error if there isn't one
 getConfiguredClient() {
   if command -v curl &>/dev/null; then
     configuredClient="curl"
@@ -46,7 +46,7 @@ getConfiguredClient() {
   elif command -v fetch &>/dev/null; then
     configuredClient="fetch"
   else
-    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
+    echo "Error: This tool requires either curl, wget, httpie or fetch to be installed." >&2
     return 1
   fi
 }
@@ -66,7 +66,7 @@ checkValidCurrency() {
   if [[ $1 != "BTC" && $1 != "ETH" &&
     $1 != "XRP" && $1 != "LTC" && $1 != "XEM" &&
     $1 != "ETC" && $1 != "DASH" && $1 != "MIOTA" &&
-    $1 != "XMR" && $1 != "STRAT" && $1 != "BCH" ]]; then
+    $1 != "XMR" && $1 != "STRAT" && $1 != "BCH" ]]; then # codespell:ignore
     echo "1"
   else
     echo "0"
@@ -86,7 +86,7 @@ checkTargetCurrency() {
 }
 
 ## Grabs the base currency from the user and validates it with all the possible currency
-## types available on the API and guides user through input (doesnt take in arguments)
+## types available on the API and guides user through input (doesn't take in arguments)
 getBase() {
   echo -n "What is the base currency: "
   read -r base
@@ -122,13 +122,13 @@ transformBase() {
   "DASH") reqId="dash" ;;
   "MIOTA") reqId="iota" ;;
   "XMR") reqId="monero" ;;
-  "STRAT") reqId="stratis" ;;
+  "STRAT") reqId="stratis" ;; # codespell:ignore
   "BCH") reqId="bitcoin-cash" ;;
   esac
 }
 
 ## Grabs the exchange to currency from the user and validates it with all the possible currency
-## types available on the API and guides user through input (doesnt take in arguments)
+## types available on the API and guides user through input (doesn't take in arguments)
 getExchangeTo() {
   echo -n "What currency to exchange to: "
   read -r exchangeTo
@@ -153,7 +153,7 @@ checkExchangeTo() {
 }
 
 ## Get the amount that will be exchanged and validate that the user has entered a number (decimals are allowed)
-## doesnt take in argument, it guides user through input
+## doesn't take in argument, it guides user through input
 getAmount() {
   echo -n "What is the amount being exchanged: "
   read -r amount
@@ -210,9 +210,9 @@ EOF
 update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
-  # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets"                                                                                                                           #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repostiory ex. alexanderepstein
+  # To test the tool enter in the default values that are in the examples for each variable
+  repositoryName="Bash-Snippets"                                                                                                                           #Name of repository to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repository ex. alexanderepstein
   nameOfInstallFile="install.sh"                                                                                                                           # change this if the installer file has a different name be sure to include file extension if there is one
   latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
@@ -252,11 +252,11 @@ update() {
           exit 1
         }
         git checkout "v$latestVersion" 2>/dev/null || git checkout "$latestVersion" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
-        chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
+        chmod a+x install.sh #this might be necessary in your case but wasn't in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
         rm -r -f $repositoryName || {
-          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
+          echo "Permissions Error: update successful but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
           exit 1
         }
       else
@@ -305,7 +305,7 @@ while getopts "of:uvh" opt; do
     exit 0
     ;;
   u)
-    checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+    checkInternet || exit 1 # check if we have a valid internet connection if this isn't true the rest of the script will not work so stop here
     update
     exit 0
     ;;
@@ -322,13 +322,13 @@ if $old; then
   getExchangeTo # get exchange to currency
   getAmount     # get the amount to be converted
   transformBase
-  convertCurrency # grab the exhange rate and perform the conversion
+  convertCurrency # grab the exchange rate and perform the conversion
   exit 0
 fi
 
 if [[ $1 == "update" ]]; then
   getConfiguredClient || exit 1
-  checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+  checkInternet || exit 1 # check if we have a valid internet connection if this isn't true the rest of the script will not work so stop here
   update
   exit 0
 elif [[ $1 == "help" ]]; then
diff --git a/bin/geo b/bin/geo
--- a/bin/geo
+++ b/bin/geo
@@ -18,7 +18,7 @@ getConfiguredClient() {
   elif command -v fetch &>/dev/null; then
     configuredClient="fetch"
   else
-    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
+    echo "Error: This tool requires either curl, wget, httpie or fetch to be installed." >&2
     return 1
   fi
 }
@@ -134,9 +134,9 @@ specific_geo() {
 update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
-  # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets"                                                                                                                           #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repostiory ex. alexanderepstein
+  # To test the tool enter in the default values that are in the examples for each variable
+  repositoryName="Bash-Snippets"                                                                                                                           #Name of repository to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repository ex. alexanderepstein
   nameOfInstallFile="install.sh"                                                                                                                           # change this if the installer file has a different name be sure to include file extension if there is one
   latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
@@ -176,11 +176,11 @@ update() {
           exit 1
         }
         git checkout "v$latestVersion" 2>/dev/null || git checkout "$latestVersion" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
-        chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
+        chmod a+x install.sh #this might be necessary in your case but wasn't in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
         rm -r -f $repositoryName || {
-          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
+          echo "Permissions Error: update successful but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
           exit 1
         }
       else
diff --git a/bin/lyrics b/bin/lyrics
--- a/bin/lyrics
+++ b/bin/lyrics
@@ -7,7 +7,7 @@ artist="false"
 song="false"
 filePath=""
 
-## This function determines which http get tool the system has installed and returns an error if there isnt one
+## This function determines which http get tool the system has installed and returns an error if there isn't one
 getConfiguredClient() {
   if command -v curl &>/dev/null; then
     configuredClient="curl"
@@ -18,7 +18,7 @@ getConfiguredClient() {
   elif command -v fetch &>/dev/null; then
     configuredClient="fetch"
   else
-    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
+    echo "Error: This tool requires either curl, wget, httpie or fetch to be installed." >&2
     return 1
   fi
 }
@@ -56,9 +56,9 @@ httpGet() {
 update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 1.2.0
-  # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets"                                                                                                                           #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repostiory ex. alexanderepstein
+  # To test the tool enter in the default values that are in the examples for each variable
+  repositoryName="Bash-Snippets"                                                                                                                           #Name of repository to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repository ex. alexanderepstein
   nameOfInstallFile="install.sh"                                                                                                                           # change this if the installer file has a different name be sure to include file extension if there is one
   latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
@@ -91,11 +91,11 @@ update() {
           exit 1
         }
         git checkout "v$latestVersion" 2>/dev/null || git checkout "$latestVersion" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
-        chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
+        chmod a+x install.sh #this might be necessary in your case but wasn't in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
         rm -r -f $repositoryName || {
-          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
+          echo "Permissions Error: update successful but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
           exit 1
         }
       else
@@ -183,12 +183,12 @@ while getopts "f:a:s:uvh" opt; do
     ;;
   a)
     artist="true"
-    if [[ "$(echo "$@" | grep -Eo "\-s")" == "-s" ]]; then song="true"; fi # wont go through both options if arg spaced and not quoted this solves that issue (dont need this but once had bug on system where it was necessary)
+    if [[ "$(echo "$@" | grep -Eo "\-s")" == "-s" ]]; then song="true"; fi # won't go through both options if arg spaced and not quoted this solves that issue (dont need this but once had bug on system where it was necessary)
     if [[ "$(echo "$@" | grep -Eo "\-f")" == "-f" ]]; then filePath=$(echo "$@" | grep -Eo "\-f [ a-z A-Z / 0-9 . \ ]*[ -]?" | sed s/-f//g | sed s/-//g | sed s/^" "//g); fi
     ;;
   s)
     song="true"
-    if [[ "$(echo "$@" | grep -Eo "\-a")" == "-a" ]]; then artist="true"; fi # wont go through both options if arg spaced and not quoted this solves that issue (dont need this but once had bug on system where it was necessary)
+    if [[ "$(echo "$@" | grep -Eo "\-a")" == "-a" ]]; then artist="true"; fi # won't go through both options if arg spaced and not quoted this solves that issue (dont need this but once had bug on system where it was necessary)
     if [[ "$(echo "$@" | grep -Eo "\-f")" == "-f" ]]; then filePath=$(echo "$@" | grep -Eo "\-f [ a-z A-Z / 0-9 . \ ]*[ -]?" | sed s/-f//g | sed s/-//g | sed s/^" "//g); fi
     ;;
   :)
@@ -236,7 +236,7 @@ elif $artist && $song; then
 else
   {
     clear
-    echo "You shouldnt be here but maaaaaaybeee you slipped passed me, learn to use the tool!"
+    echo "You shouldn't be here but maaaaaaybeee you slipped passed me, learn to use the tool!"
     sleep 5
     clear
   }
diff --git a/bin/movies b/bin/movies
--- a/bin/movies
+++ b/bin/movies
@@ -6,7 +6,7 @@ configuredClient=""
 configuredPython=""
 detail=false
 
-## This function determines which http get tool the system has installed and returns an error if there isnt one
+## This function determines which http get tool the system has installed and returns an error if there isn't one
 getConfiguredClient() {
   if command -v curl &>/dev/null; then
     configuredClient="curl"
@@ -17,7 +17,7 @@ getConfiguredClient() {
   elif command -v fetch &>/dev/null; then
     configuredClient="fetch"
   else
-    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
+    echo "Error: This tool requires either curl, wget, httpie or fetch to be installed." >&2
     return 1
   fi
 }
@@ -117,9 +117,9 @@ printMovieInfo() {
 update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
-  # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets"                                                                                                                           #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repostiory ex. alexanderepstein
+  # To test the tool enter in the default values that are in the examples for each variable
+  repositoryName="Bash-Snippets"                                                                                                                           #Name of repository to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repository ex. alexanderepstein
   nameOfInstallFile="install.sh"                                                                                                                           # change this if the installer file has a different name be sure to include file extension if there is one
   latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
@@ -159,11 +159,11 @@ update() {
           exit 1
         }
         git checkout "v$latestVersion" 2>/dev/null || git checkout "$latestVersion" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
-        chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
+        chmod a+x install.sh #this might be necessary in your case but wasn't in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
         rm -r -f $repositoryName || {
-          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
+          echo "Permissions Error: update successful but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
           exit 1
         }
       else
@@ -196,7 +196,7 @@ getConfiguredClient || exit 1
 while getopts 'ud:hv' flag; do
   case "${flag}" in
   u)
-    checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+    checkInternet || exit 1 # check if we have a valid internet connection if this isn't true the rest of the script will not work so stop here
     update
     exit 0
     ;;
@@ -220,12 +220,12 @@ done
 if [[ $# == 0 ]]; then
   usage
 elif [[ $1 == "update" ]]; then
-  checkInternet || exit 1 # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+  checkInternet || exit 1 # check if we have a valid internet connection if this isn't true the rest of the script will not work so stop here
   update
 elif [[ $1 == "help" ]]; then
   usage
 else
-  checkInternet || exit 1     # check if we have a valid internet connection if this isnt true the rest of the script will not work so stop here
+  checkInternet || exit 1     # check if we have a valid internet connection if this isn't true the rest of the script will not work so stop here
   getMovieInfo "$@" || exit 1 ## exit if we return 1 (chances are movie was not found)
   printMovieInfo              ## print out the data
 fi
diff --git a/bin/transfer b/bin/transfer
--- a/bin/transfer
+++ b/bin/transfer
@@ -6,7 +6,7 @@ configuredClient=""
 currentVersion="1.22.0"
 down="false"
 
-## This function determines which http get tool the system has installed and returns an error if there isnt one
+## This function determines which http get tool the system has installed and returns an error if there isn't one
 getConfiguredDownloadClient() {
   if command -v curl &>/dev/null; then
     configuredDownloadClient="curl"
@@ -15,7 +15,7 @@ getConfiguredDownloadClient() {
   elif command -v fetch &>/dev/null; then
     configuredDownloadClient="fetch"
   else
-    echo "Error: Downloading with this tool reqires either curl, wget, or fetch to be installed." >&2
+    echo "Error: Downloading with this tool requires either curl, wget, or fetch to be installed." >&2
     return 1
   fi
 }
@@ -30,7 +30,7 @@ httpGet() {
   esac
 }
 
-## This function determines which http get tool the system has installed and returns an error if there isnt one
+## This function determines which http get tool the system has installed and returns an error if there isn't one
 getConfiguredClient() {
   if command -v curl &>/dev/null; then
     configuredClient="curl"
@@ -41,19 +41,19 @@ getConfiguredClient() {
   elif command -v fetch &>/dev/null; then
     configuredClient="fetch"
   else
-    echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
+    echo "Error: This tool requires either curl, wget, httpie or fetch to be installed." >&2
     return 1
   fi
 }
 
-## This function determines which http get tool the system has installed and returns an error if there isnt one
+## This function determines which http get tool the system has installed and returns an error if there isn't one
 getconfiguredUploadClient() {
   if command -v curl &>/dev/null; then
     configuredUploadClient="curl"
   elif command -v wget &>/dev/null; then
     configuredUploadClient="wget"
   else
-    echo "Error: Uploading with this tool reqires either curl or wget to be installed." >&2
+    echo "Error: Uploading with this tool requires either curl or wget to be installed." >&2
     return 1
   fi
 }
@@ -78,9 +78,9 @@ httpDownload() {
 update() {
   # Author: Alexander Epstein https://github.com/alexanderepstein
   # Update utility version 2.2.0
-  # To test the tool enter in the defualt values that are in the examples for each variable
-  repositoryName="Bash-Snippets"                                                                                                                           #Name of repostiory to be updated ex. Sandman-Lite
-  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repostiory ex. alexanderepstein
+  # To test the tool enter in the default values that are in the examples for each variable
+  repositoryName="Bash-Snippets"                                                                                                                           #Name of repository to be updated ex. Sandman-Lite
+  githubUserName="alexanderepstein"                                                                                                                        #username that hosts the repository ex. alexanderepstein
   nameOfInstallFile="install.sh"                                                                                                                           # change this if the installer file has a different name be sure to include file extension if there is one
   latestVersion=$(httpGet https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",' | head -1 | grep -Eo "[0-9.]+") #always grabs the tag without the v option
 
@@ -120,11 +120,11 @@ update() {
           exit 1
         }
         git checkout "v$latestVersion" 2>/dev/null || git checkout "$latestVersion" 2>/dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
-        chmod a+x install.sh #this might be necessary in your case but wasnt in mine.
+        chmod a+x install.sh #this might be necessary in your case but wasn't in mine.
         ./$nameOfInstallFile "update" || exit 1
         cd ..
         rm -r -f $repositoryName || {
-          echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
+          echo "Permissions Error: update successful but cannot delete temp files located at ~/$repositoryName delete this directory with sudo"
           exit 1
         }
       else
@@ -150,7 +150,7 @@ singleDownload() {
   }; fi
   tempOutputPath=$1
   if [ -f "$tempOutputPath/$3" ]; then
-    echo -n "File aleady exists at $tempOutputPath/$3, do you want to delete it? [Y/n] "
+    echo -n "File already exists at $tempOutputPath/$3, do you want to delete it? [Y/n] "
     read -r answer
     if [[ "$answer" == [Yy] ]]; then
       rm -f $tempOutputPath/$3
